### ISSUE TITLE
CSS Background in Text Editor area

### ISSUE THREAD

**Issue by ultramagnes23** [fernandovega/time_theme#2]
When i enable Time_Theme plugin, the ckeditor text space is replaced with the background image.
![css problem](https://cloud.githubusercontent.com/assets/16393778/11945160/57dea7b2-a812-11e5-9c11-afcfe83087e8.jpg)

**Comment by ultramagnes23** [comment]
Nevermind, i got it. Modify mod/ckeditor/views/default/css/elgg/wysiwyg.css

under Body{
margin: 8px;
-add-
background:#EBF5FF;
-or whatever color you want-
issue is with ckeditor.
![css problem](https://cloud.githubusercontent.com/assets/16393778/11945383/fb34c124-a814-11e5-943b-468aa471d12b.jpg)

**Comment by fernandovega** [comment]
Thanks

Check the Pro version of Time Theme with support for elgg 2.0

https://github.com/fernandovega/time_theme_pro/tree/2.0
